export const GET_WEATHER_CARDS = "GET_WEATHER_CARDS";
export const PATCH_WEATHER_CARD = "PATCH_WEATHER_CARD";
export const ERROR_WEATHER_CARD = "ERROR_WEATHER_CARD";
export const UPDATE_START_WEATHER = "UPDATE_START_WEATHER";
export const DELETE_WEATHER_CARD = "DELETE_WEATHER_CARD";
